//
// Created by Daniel Shih on 12/28/17.
//

#ifndef BUMPKININTERPRETER_LINELABELTYPE_HPP
#define BUMPKININTERPRETER_LINELABELTYPE_HPP

enum LineLabelType{NUMBER, LABEL};

#endif //BUMPKININTERPRETER_LINELABELTYPE_HPP
