//
// Created by Daniel Shih on 12/28/17.
//

#ifndef BUMPKININTERPRETER_RELATIONALOPERATOR_HPP
#define BUMPKININTERPRETER_RELATIONALOPERATOR_HPP

enum RelationalOperator {EQ, NOT_EQ, LESS, LESS_EQ, GREATER, GREATER_EQ};

#endif //BUMPKININTERPRETER_RELATIONALOPERATOR_HPP
